### ISSUE TITLE
Sticky Password Manager Logo

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#100]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.stickypassword.com/
2. **Exact Service Name** displayed in the app
Sticky Password
3. Upload the logo in 90x90, logo should be square
![sticky90](https://user-images.githubusercontent.com/25370801/33026714-488e1534-cdce-11e7-8cd7-a6265cb18848.png)

**Comment by MufriA** [comment]
We already have this in our db, please wait for the app to load or kill the app and open again.

Reopen the issue if still you couldn't see the logo.
