### ISSUE TITLE
GBATemp Logo

### ISSUE THREAD

**Issue by TBJ** [authenticatorplus/logos#101]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine: **_[www.gbatemp.net](https://gbatemp.net/)_**
2. Exact Service Name displayed in the app: **_GBATemp_**
3. Upload the logo in 90x90, logo should be square: 
![tempy](https://user-images.githubusercontent.com/22847104/33228831-edc2231e-d180-11e7-8e00-a4e6b13d384f.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
