### ISSUE TITLE
Apache Guacamole

### ISSUE THREAD

**Issue by flamechair** [authenticatorplus/logos#102]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine

https://guacamole.apache.org/

2. **Exact Service Name** displayed in the app

"Apache Guacamole"

3. Upload the logo in 90x90, logo should be square

![guacamole](https://user-images.githubusercontent.com/8901422/33273330-96654ff0-d352-11e7-886a-d52f2c29b738.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
