### ISSUE TITLE
Logo request

### ISSUE THREAD

**Issue by anony253** [authenticatorplus/logos#103]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
www.ripe.net
2. **Exact Service Name** displayed in the app
RIPE NCC
3. Upload the logo in 90x90, logo should be square
https://static.anony253.net/images-oth/ripe_ncc.png

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
