### ISSUE TITLE
Logo Request: Scaleway

### ISSUE THREAD

**Issue by andydvsn** [authenticatorplus/logos#105]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine

https://www.scaleway.com/

2. **Exact Service Name** displayed in the app

Scaleway

3. Upload the logo in 90x90, logo should be square

Attached as a .PNG.

![scaleway](https://user-images.githubusercontent.com/1003682/33878854-8819c150-df24-11e7-8a60-4af96bbf3a64.png)

**Comment by andydvsn** [comment]
Also, white-backed version if necessary.

![scaleway](https://user-images.githubusercontent.com/1003682/33878896-a942d4ca-df24-11e7-8bf5-8e236a9f3875.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
