### ISSUE TITLE
Logo request HashFlare

### ISSUE THREAD

**Issue by riaan53** [authenticatorplus/logos#106]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://hashflare.io/
2. **Exact Service Name** displayed in the app
HashFlare - HashFlare - HashFlare - "useremail"
3. Upload the logo in 90x90, logo should be square
![hashlogo](https://user-images.githubusercontent.com/7716342/34077859-bac6e754-e316-11e7-8fc1-6b3324891c9a.png)

**Comment by mKoonrad** [comment]
@MufriA We are waiting for update

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
