### ISSUE TITLE
Logo request: Binance

### ISSUE THREAD

**Issue by riaan53** [authenticatorplus/logos#108]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.binance.com/
2. **Exact Service Name** displayed in the app
Binance.com - Binance.com - Binance.com - "useremail"
3. Upload the logo in 90x90, logo should be square
![binance_logo](https://user-images.githubusercontent.com/7716342/34201314-c8742002-e57c-11e7-8435-619fd88d2c9c.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
