### ISSUE TITLE
Logo Request

### ISSUE THREAD

**Issue by mstarks01** [authenticatorplus/logos#109]
Please provide below info, all are mandatory

1. https://www.issafortworth.org
2. ISSA, Fort Worth Chapter
3. Logo attached

Thank you!
![issafw-authenticator](https://user-images.githubusercontent.com/459717/34642146-f87ff9c4-f2d3-11e7-8e42-4dd29f303322.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
