### ISSUE TITLE
CoinSpot Icon Request

### ISSUE THREAD

**Issue by RCourtenay** [authenticatorplus/logos#110]
Please provide below info, all are mandatory

1. https://www.coinspot.com.au
2. CoinSpot
3. Upload the logo in 90x90, logo should be square

![coinspot](https://user-images.githubusercontent.com/29133455/34648340-6fe7a458-f3ec-11e7-9c9c-84a1d65ad30a.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by RCourtenay** [comment]
Hi. Unable to see this one currently in the icon selection screen.
