### ISSUE TITLE
Bitstamp Icon Request

### ISSUE THREAD

**Issue by RCourtenay** [authenticatorplus/logos#111]
Please provide below info, all are mandatory

1. https://www.bitstamp.net/
2. Bitstamp
3. Upload the logo in 90x90, logo should be square
![bitstamp](https://user-images.githubusercontent.com/29133455/34648413-eee521fe-f3ec-11e7-8607-ac71a7debef4.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
