### ISSUE TITLE
Fishpond Logo Request

### ISSUE THREAD

**Issue by RCourtenay** [authenticatorplus/logos#112]
Please provide below info, all are mandatory

1. https://www.fishpond.com.au
2. Fishpond - Fishpond - Fishpond - "useremail"
3. Upload the logo in 90x90, logo should be square
![fishpond](https://user-images.githubusercontent.com/29133455/34648503-5e1bc130-f3ee-11e7-8929-405d304d8b57.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
