### ISSUE TITLE
Bittrex.com

### ISSUE THREAD

**Issue by nstetter** [authenticatorplus/logos#114]

**Comment by HomeY** [comment]
Seems it's removed, so here is it again:

Website URL of server, even twitter page of the service too is fine
https://bittrex.com/

Exact Service Name displayed in the app
Bittrex

Upload the logo in 90x90, logo should be square
![bittrex](https://user-images.githubusercontent.com/1996332/37908318-304a504e-3108-11e8-8190-c476951fb09b.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
