### ISSUE TITLE
NPM logo

### ISSUE THREAD

**Issue by Caligatio** [authenticatorplus/logos#115]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.npmjs.com/
2. **Exact Service Name** displayed in the app
NPM
3. Upload the logo in 90x90, logo should be square
![npm](https://user-images.githubusercontent.com/2017685/35219584-2bbfebfc-ff6b-11e7-8a43-b2feef8c9a56.png)

Icon taken from https://github.com/npm/logos/blob/master/npm%20square/n-large.png

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by siburny** [comment]
For some reason, this logo is not available in the app itself. Am I missing something?

**Comment by avargaskun** [comment]
@MufriA - I'm also not seeing this logo in the app. I'm in version 2.3 for iOS. Any ideas?
