### ISSUE TITLE
Betterment

### ISSUE THREAD

**Issue by keatongreve** [authenticatorplus/logos#116]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.betterment.com
2. Exact Service Name displayed in the app
Betterment
3. Upload the logo in 90x90, logo should be square
![betterment](https://user-images.githubusercontent.com/596193/35252411-f752a874-ffa5-11e7-8dcb-93f718d50c3e.png)

**Comment by keatongreve** [comment]
I should add, I noticed that this was reported last year, but it doesn't seem to be showing up in the logo options. Play Store version 3.8.7

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
