### ISSUE TITLE
Dynadot

### ISSUE THREAD

**Issue by dieskim** [authenticatorplus/logos#12]
Please provide below info, all are mandatory

1. www.dynadot.com
2. Dynadot
3. 
![dynadot](https://cloud.githubusercontent.com/assets/9603625/24941556/8aa2b694-1f75-11e7-87c7-331e0b8d5b05.png)

**Comment by MufriA** [comment]
We already have this in our db, please wait for the app to load or kill the app and open again.

Reopen the issue if still you couldn't see the logo.
