### ISSUE TITLE
anti-captcha.com

### ISSUE THREAD

**Issue by kowalskey** [authenticatorplus/logos#120]
Hello!
Please add icon for anti-captcha.com (captcha solving as service) 2FA.

1. URL: https://anti-captcha.com
2. Servicename: `anticaptcha`
3. ![ac](https://user-images.githubusercontent.com/9946457/35289978-2434c2a0-0069-11e8-9336-5d0f06e80d65.png)

thanks in advance!

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
