### ISSUE TITLE
Logo request: PIX System

### ISSUE THREAD

**Issue by kangstarr** [authenticatorplus/logos#121]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
http://www.pixsystem.com

2. **Exact Service Name** displayed in the app
PIX System

3. Upload the logo in 90x90, logo should be square
![pixsystem_square_logo](https://user-images.githubusercontent.com/17909854/35658848-259dcd4e-06b8-11e8-8645-830add6f0606.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
