### ISSUE TITLE
Gate.io

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#122]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://gate.io/
2. **Exact Service Name** displayed in the app
Gate.io
3. Upload the logo in 90x90, logo should be square
![gate](https://user-images.githubusercontent.com/25370801/35740749-09d7d9a6-07f3-11e8-87a2-cf46d8ffc33f.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
