### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#123]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://privacy.com/
2. **Exact Service Name** displayed in the app
Privacy

3. Upload the logo in 90x90, logo should be square
![privacy](https://user-images.githubusercontent.com/25370801/35740869-67da1ae6-07f3-11e8-88a8-cb4b92fb4ac4.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
