### ISSUE TITLE
TurboTax

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#124]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://turbotax.intuit.com/
2. **Exact Service Name** displayed in the app
Turbo Tax
3. Upload the logo in 90x90, logo should be square
![turbotax](https://user-images.githubusercontent.com/25370801/35741004-d4239aba-07f3-11e8-8532-ce712d04e6b2.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
