### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#125]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://github.com
2. **Exact Service Name** displayed in the app
GitHub
3. Upload the logo in 90x90, logo should be square
![github blue](https://user-images.githubusercontent.com/25370801/35741193-60a55960-07f4-11e8-996c-f1ed7403c9ac.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
