### ISSUE TITLE
Dnsmanager

### ISSUE THREAD

**Issue by egmose** [authenticatorplus/logos#127]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
Dnsmanager.io

2. **Exact Service Name** displayed in the app

DNSmanager

3. Upload the logo in 90x90, logo should be square
https://app.dnsmanager.io/favicon.ico

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
