### ISSUE TITLE
Reddit

### ISSUE THREAD

**Issue by silver886** [authenticatorplus/logos#128]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
reddit.com
2. **Exact Service Name** displayed in the app
Reddit
3. Upload the logo in 90x90, logo should be square
https://images-na.ssl-images-amazon.com/images/I/418PuxYS63L.png

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
