### ISSUE TITLE
Mailgun

### ISSUE THREAD

**Issue by silver886** [authenticatorplus/logos#129]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
mailgun.com
2. **Exact Service Name** displayed in the app
Mailgun
3. Upload the logo in 90x90, logo should be square
https://cdn.slant.co/179211af-7d7c-4a7b-b2d6-9bdd8930c147/-/format/jpeg/-/progressive/yes/-/preview/480x480/

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
