### ISSUE TITLE
Adobe

### ISSUE THREAD

**Issue by silver886** [authenticatorplus/logos#130]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
adobe.com
2. **Exact Service Name** displayed in the app
Adobe
3. Upload the logo in 90x90, logo should be square
https://media-exp2.licdn.com/media/AAIAAgDGAAoAAQAAAAAAAA6AAAAAJDE2OTgyYzJhLTYzYTktNDhmNi1hMzJlLWYyODY3MzVkMTRlNg.png

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by EDIflyer** [comment]
Hi Mufri - I've just added an Adobe account but it's not showing the logo?  I went to request it then found this case saying it had already been added - however when I pick custom icon I can't see Adobe in the list?

**Comment by curtismorrison** [comment]
Mufri - That Adobe logo is still NOT available on the most recent iOS app.

**Comment by EDIflyer** [comment]
Nor Android...

**Comment by curtismorrison** [comment]
What is the objective in terms of turn-around time for new logo requests for this paid app? I think my last request was six months ago and it still isn't working.
