### ISSUE TITLE
Please add Synergy-Wholesale Icon

### ISSUE THREAD

**Issue by screenbeard** [authenticatorplus/logos#131]
1. https://manage.synergywholesale.com
2. Synergy-Wholesale
3. ![synergy_wholesale_logo_large](https://user-images.githubusercontent.com/3305119/37286044-bdbc0610-2650-11e8-9194-7d7e3185fca6.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by screenbeard** [comment]
@MufriA Would you believe they changed their logo two weeks ago?

![synergy](https://user-images.githubusercontent.com/3305119/40149280-f8538da4-59b1-11e8-9dd0-1b59f0388eb0.png)

**Comment by screenbeard** [comment]
Whoops, I didn't resize to 90x90

![synergy](https://user-images.githubusercontent.com/3305119/40149316-2063c070-59b2-11e8-93c6-0f221ed15c28.png)

**Comment by MufriA** [comment]
Updated to new logo.
