### ISSUE TITLE
Koinex

### ISSUE THREAD

**Issue by raisedadead** [authenticatorplus/logos#132]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine

https://koinex.in/

2. **Exact Service Name** displayed in the app

Koinex

3. Upload the logo in 90x90, logo should be square

![koinex](https://user-images.githubusercontent.com/1884376/37331221-5ba443d8-26c9-11e8-8b16-45eabad23665.jpeg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
