### ISSUE TITLE
Update Bitbucket Logo to Latest

### ISSUE THREAD

**Issue by raisedadead** [authenticatorplus/logos#133]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine

https://bitbucket.org

2. **Exact Service Name** displayed in the app

Bitbucket

3. Upload the logo in 90x90, logo should be square

![bitbucket](https://user-images.githubusercontent.com/1884376/37331383-c702453a-26c9-11e8-9e3d-55f141be1cc6.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
