### ISSUE TITLE
Favicon as logo

### ISSUE THREAD

**Issue by Muenchen-Michi** [authenticatorplus/logos#138]
It would be great if Authenticator-Plus could download the favicon of a website, using it as logo. I have a lot of websites running joomla, and the joomla-logo for every code doesn't help a lot. On the other hand I don't want to download the logo, save it on the device and select it in Authenticator-Plus.

Maybe by using the url as name of the service or by having a additional logo-button (like the first custom-logo) and after this I've to enter the url.

**Comment by MufriA** [comment]
I have tried this approach earlier, most of the sites has bad quality logo, anyways that was years ago, i could try again, if no logo is present i can fallback to favicon.
