### ISSUE TITLE
LiteBit.eu

### ISSUE THREAD

**Issue by HomeY** [authenticatorplus/logos#139]
Seems it was added before but somehow got removed, so here is it again

Please provide below info, all are mandatory
1. Website URL of server, even twitter page of the service too is fine
https://www.litebit.eu/

2. **Exact Service Name** displayed in the app
LiteBit

3. Upload the logo in 90x90, logo should be square
![litebit](https://user-images.githubusercontent.com/1996332/37908608-067c2bc4-3109-11e8-8ea4-655c1488527e.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
