### ISSUE TITLE
CoinTracking.info

### ISSUE THREAD

**Issue by HomeY** [authenticatorplus/logos#140]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://cointracking.info

2. **Exact Service Name** displayed in the app
CoinTracking

3. Upload the logo in 90x90, logo should be square
![cointracking](https://user-images.githubusercontent.com/1996332/37908683-2e8cda50-3109-11e8-8fee-f75848e74360.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
