### ISSUE TITLE
GateHub.net

### ISSUE THREAD

**Issue by HomeY** [authenticatorplus/logos#141]
Website URL of server, even twitter page of the service too is fine
https://www.gatehub.net/

Exact Service Name displayed in the app
GateHub

Upload the logo in 90x90, logo should be square
![gatehub](https://user-images.githubusercontent.com/1996332/37908817-90f27aa6-3109-11e8-85c1-166ca3152ce6.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
