### ISSUE TITLE
HitBTC.com

### ISSUE THREAD

**Issue by HomeY** [authenticatorplus/logos#142]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://hitbtc.com/

2. **Exact Service Name** displayed in the app
HitBTC

3. Upload the logo in 90x90, logo should be square
![hitbtc](https://user-images.githubusercontent.com/1996332/37908865-aeca17d2-3109-11e8-88a5-f18a397cda28.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
