### ISSUE TITLE
KuCoin.com

### ISSUE THREAD

**Issue by HomeY** [authenticatorplus/logos#143]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.kucoin.com

2. **Exact Service Name** displayed in the app
KuCoin

3. Upload the logo in 90x90, logo should be square
![kucoin](https://user-images.githubusercontent.com/1996332/37908897-c01490f8-3109-11e8-877a-68c01a73b4af.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
