### ISSUE TITLE
OKEx.com

### ISSUE THREAD

**Issue by HomeY** [authenticatorplus/logos#144]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.okex.com

2. **Exact Service Name** displayed in the app
OKEx

3. Upload the logo in 90x90, logo should be square
![okex](https://user-images.githubusercontent.com/1996332/37908916-cef0d816-3109-11e8-9a95-28309f88bec6.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
