### ISSUE TITLE
USA Jobs/Login.gov

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#147]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://login.gov/
2. **Exact Service Name** displayed in the app
login.gov
3. Upload the logo in 90x90, logo should be square
![loginauth](https://user-images.githubusercontent.com/25370801/40129655-144784e0-58f2-11e8-830d-70b3ca0a4d5c.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
