### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#148]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.mozilla.org
2. **Exact Service Name** displayed in the app
Firefox
3. Upload the logo in 90x90, logo should be square
![rsz_mozilla-firefox-icon-4032](https://user-images.githubusercontent.com/25370801/40463618-7b136310-5ed3-11e8-9ccc-3dc9e1ba871e.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
