### ISSUE TITLE
Protonmail

### ISSUE THREAD

**Issue by Riajyuu** [authenticatorplus/logos#149]
URL; protonmail.com
Name: ProtonMail
logo 

![export_1](https://user-images.githubusercontent.com/16912240/41398034-8bdbbd0e-6fa5-11e8-8f70-308e869975f9.png)

**Comment by Riajyuu** [comment]
Another question here:
I saw Firefox from #148 ,but why can't I see that in Authentication Plus?

**Comment by MufriA** [comment]
If the service name is Firefox it will display
