### ISSUE TITLE
Eve Online

### ISSUE THREAD

**Issue by TiiFuchs** [authenticatorplus/logos#150]
Please provide below info, all are mandatory

1. https://eveonline.com
2. Eve Online
3. ![13510900_10154323441489394_5051214450340102581_n](https://user-images.githubusercontent.com/1958744/41425432-fab9b69e-7000-11e8-90ff-356b95d8600e.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
