### ISSUE TITLE
Humble Bundle

### ISSUE THREAD

**Issue by TiiFuchs** [authenticatorplus/logos#151]
Please provide below info, all are mandatory

1. https://www.humblebundle.com
2. Humble Bundle
3. 
![10402552_910781385631833_1137863093623282754_n](https://user-images.githubusercontent.com/1958744/41425494-3b8ddd3a-7001-11e8-9921-e4ee7b74fd08.png)

**Comment by jelbo** [comment]
![humble bundle](https://user-images.githubusercontent.com/7387027/41508716-528403da-7249-11e8-9c53-e39f224a92cb.png)

**Comment by MufriA** [comment]
Updated the logo.
