### ISSUE TITLE
Reddit

### ISSUE THREAD

**Issue by jelbo** [authenticatorplus/logos#156]
Please provide below info, all are mandatory

1. https://www.reddit.com
2. Reddit
3. 
![reddit](https://user-images.githubusercontent.com/7387027/41508767-05361d7e-724a-11e8-9281-3785d4e4181e.png)

**Comment by MufriA** [comment]
We already have this in our db, please wait for the app to load or kill the app and open again.

Reopen the issue if still you couldn't see the logo.
