### ISSUE TITLE
Logo requests

### ISSUE THREAD

**Issue by NeodiumNetwork** [authenticatorplus/logos#158]
The names are **Exact Service Name displayed in the app**

Bibox
![bibox com](https://user-images.githubusercontent.com/39248042/42054179-62690f26-7b1c-11e8-84d1-aa15bdfbf906.png)

Bitfinex
![bitfinex com](https://user-images.githubusercontent.com/39248042/42054180-62a01ff2-7b1c-11e8-8e78-fe1d3c6d0557.png)

BitFlip.cc
![bitflip li](https://user-images.githubusercontent.com/39248042/42054181-62c58a4e-7b1c-11e8-8730-ca2e3b97efe4.png)

Bitgrail
![bitgrail com](https://user-images.githubusercontent.com/39248042/42054182-62eb3cee-7b1c-11e8-8a72-c72a4adc1e40.png)

Bittrex
![bittrex com](https://user-images.githubusercontent.com/39248042/42054183-63146bf0-7b1c-11e8-9c72-6540aa6e0f56.png)

Bit-Z
![bit-z com](https://user-images.githubusercontent.com/39248042/42054185-633f739a-7b1c-11e8-8bdf-8c7617e40ff3.png)

blockchain.info
![blockchain com](https://user-images.githubusercontent.com/39248042/42054186-63644152-7b1c-11e8-9663-7a2d3aa03298.png)

btc-alpha.com
![btc-alpha com](https://user-images.githubusercontent.com/39248042/42054187-63896310-7b1c-11e8-9e17-8875a992bd76.png)

COBINHOOD
![cobinhood com](https://user-images.githubusercontent.com/39248042/42054190-63b95944-7b1c-11e8-978d-8fb0b50aa7be.png)

Coinbene
![coinbene com](https://user-images.githubusercontent.com/39248042/42054191-63e87bc0-7b1c-11e8-93fe-019df1146ee2.png)

www.coinex.com
![coinex com](https://user-images.githubusercontent.com/39248042/42054192-640f766c-7b1c-11e8-9679-dafdcf5fc6da.png)

Coinflux
![coinflux com](https://user-images.githubusercontent.com/39248042/42054194-643e60ee-7b1c-11e8-8ff7-b5395cff16e4.png)

Coss
![coss io](https://user-images.githubusercontent.com/39248042/42054195-64642e78-7b1c-11e8-9bdb-c23823a2ccac.png)

Cryptopia
![cryptopia co nz](https://user-images.githubusercontent.com/39248042/42054196-6488a97e-7b1c-11e8-9dca-47980c368a65.png)

GarlicWallet
![garlicoin wallet](https://user-images.githubusercontent.com/39248042/42054197-64af178a-7b1c-11e8-92cc-4d17dec3d6fd.png)

Gate.io
![gate io](https://user-images.githubusercontent.com/39248042/42054198-6535b6a0-7b1c-11e8-93d2-12c4206fec80.png)

graviex.net
![graviex net](https://user-images.githubusercontent.com/39248042/42054199-655e7a86-7b1c-11e8-963e-b0a6e1055d1e.png)

HitBTC
![hitbtc com](https://user-images.githubusercontent.com/39248042/42054200-65866a6e-7b1c-11e8-9b06-b32269e2bc04.png)

Huobi
![huobi pro](https://user-images.githubusercontent.com/39248042/42054201-65ad91de-7b1c-11e8-8315-c1081c1b6f4b.png)

Kucoin
![kucoin com](https://user-images.githubusercontent.com/39248042/42054203-65d35d42-7b1c-11e8-9438-67f80287230d.png)

LiteVaultWallet
![litevault wallet](https://user-images.githubusercontent.com/39248042/42054204-65ffcf76-7b1c-11e8-9ad4-22b103fd184c.png)

Mercatox
![mercatox com](https://user-images.githubusercontent.com/39248042/42054205-662ac082-7b1c-11e8-8066-e198722be3db.png)

Nanex.co
![nanex co](https://user-images.githubusercontent.com/39248042/42054206-6651ba3e-7b1c-11e8-9c26-aaa298401729.png)

OKex.com
![okex com](https://user-images.githubusercontent.com/39248042/42054207-6678a8f6-7b1c-11e8-953e-3f3f94f7c288.png)

Quoine
![quoine com](https://user-images.githubusercontent.com/39248042/42054208-66a215c4-7b1c-11e8-9766-4cd73481f761.png)

RETN Deals
![retn deals](https://user-images.githubusercontent.com/39248042/42054209-66c8ec94-7b1c-11e8-89d6-b94226a04309.png)

SALT Lending
![saltlending com](https://user-images.githubusercontent.com/39248042/42054210-66eee50c-7b1c-11e8-8fe8-de2d1fc85d73.png)

Stocks.Exchange
![stocks exchange](https://user-images.githubusercontent.com/39248042/42054211-6715ba10-7b1c-11e8-9330-05c9805b07d3.png)

tidex
![tidex com](https://user-images.githubusercontent.com/39248042/42054212-673cca1a-7b1c-11e8-88d7-af8715ce680c.png)

Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
2. **Exact Service Name** displayed in the app
3. Upload the logo in 90x90, logo should be square

**Comment by MufriA** [comment]
Merged all the logos.
