### ISSUE TITLE
Boxcryptor

### ISSUE THREAD

**Issue by FlorianObermayer** [authenticatorplus/logos#159]
**Url:** www.boxcryptor.com
**Service Name:** Boxcryptor
**Logo:** ![boxcryptor_logo_90x90.png](https://user-images.githubusercontent.com/4497761/42098938-8708fd32-7bbc-11e8-9052-420b3f584ee2.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
