### ISSUE TITLE
Betterment

### ISSUE THREAD

**Issue by gesquive** [authenticatorplus/logos#16]
Please provide below info, all are mandatory

1. Website URL: https://betterment.com
2. **Exact Service Name**: Betterment - Betterment
3. ![betterment](https://cloud.githubusercontent.com/assets/450565/25540698/a752a170-2c11-11e7-82d2-19c176a37036.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
