### ISSUE TITLE
AVM Fritz!Box

### ISSUE THREAD

**Issue by marcus42** [authenticatorplus/logos#160]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
2. **Exact Service Name** displayed in the app
3. Upload the logo in 90x90, logo should be square

1. www.avm.de (a popular German Internet-Router)
2 Fritz!Box

![9px-fritz _logo svg](https://user-images.githubusercontent.com/876751/43365849-7a0f287a-9333-11e8-92ff-3bd297591476.png)

**Comment by MufriA** [comment]
What is the service name displayed in app?
