### ISSUE TITLE
New logo requests

### ISSUE THREAD

**Issue by gio-vanni** [authenticatorplus/logos#161]
1. Website URL of server, even twitter page of the service too is fine
https://www.fidelity.com/

2. **Exact Service Name** displayed in the app
Fidelity

3. Upload the logo in 90x90, logo should be square
![fidelity_logo](https://user-images.githubusercontent.com/41984681/43508267-72b93032-953d-11e8-9111-ceedc46c0f30.jpg)

---

1. Website URL of server, even twitter page of the service too is fine
https://www.aol.com/

2. **Exact Service Name** displayed in the app
AOL

3. Upload the logo in 90x90, logo should be square
![aol_logo](https://user-images.githubusercontent.com/41984681/43508369-b54fa05c-953d-11e8-9601-a2c18793f515.png)

---

1. Website URL of server, even twitter page of the service too is fine
https://sourceforge.net/

2. **Exact Service Name** displayed in the app
SourceForge

3. Upload the logo in 90x90, logo should be square
![sourceforge_logo](https://user-images.githubusercontent.com/41984681/43508484-0587a48e-953e-11e8-8cb4-7421a572c956.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
