### ISSUE TITLE
Can you sync Custom Logos?

### ISSUE THREAD

**Issue by gio-vanni** [authenticatorplus/logos#162]
Can you sync custom logos between multiple devices?
Where the custom logos are stored? Where the config file is stored?

I would suggest custom logos to be stored in the database, so they could be sync'ed between multiple devices.

Also, where is the location of custom logos and the config files so they can be easily transferred?

**Comment by MufriA** [comment]
Custom logos are not synced across devices, custom logos can be anywhere in you phone, custom logos are what you pick.
