### ISSUE TITLE
Gitlab logo

### ISSUE THREAD

**Issue by dpicky** [authenticatorplus/logos#163]
1. https://gitlab.com
2. Gitlab
3. ![gitlab](https://user-images.githubusercontent.com/1231697/44212288-db206380-a162-11e8-8f9f-129ff540d3d2.png)

---
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
2. **Exact Service Name** displayed in the app
3. Upload the logo in 90x90, logo should be square

**Comment by MufriA** [comment]
We already have this in our db, please wait for the app to load or kill the app and open again.

Reopen the issue if still you couldn't see the logo.
