### ISSUE TITLE
Epic Games Logo

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#164]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.epicgames.com
2. **Exact Service Name** displayed in the app
Epic Games
3. Upload the logo in 90x90, logo should be square
![epicgames90](https://user-images.githubusercontent.com/25370801/44549311-f0a30980-a6dd-11e8-9806-54e25e99bab5.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
