### ISSUE TITLE
OpenVPN logo

### ISSUE THREAD

**Issue by pearcem0** [authenticatorplus/logos#165]
Please provide below info, all are mandatory

1. Website URL of server - https://openvpn.net
2. **Exact Service Name** displayed in the app - OpenVPN
3. Upload the logo in 90x90, logo should be square - attached
![ovpnlogo](https://user-images.githubusercontent.com/4220120/44796795-a8845b00-aba5-11e8-861f-9141b202c7bf.jpg)

**Comment by MufriA** [comment]
this logo is already there is it not opening?

**Comment by pearcem0** [comment]
No, I've tried waiting a while but it's not showing with the rest of the logos when changing a logo.
