### ISSUE TITLE
FastMail Logo Request

### ISSUE THREAD

**Issue by kwright510** [authenticatorplus/logos#166]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
2. **Exact Service Name** displayed in the app
3. Upload the logo in 90x90, logo should be square

1. https://www.fastmail.com AND https://www.fastmail.com/about/press.html
![blue-on-transparent](https://user-images.githubusercontent.com/13283029/45250080-cd897400-b2f1-11e8-8dc3-5488ccfcf930.png)
2. FastMail
3.  See Attached

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
