### ISSUE TITLE
Protonmail

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#168]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://protonmail.com
2. **Exact Service Name** displayed in the app
ProtonMail
3. Upload the logo in 90x90, logo should be square
![proton90](https://user-images.githubusercontent.com/25370801/45367116-ba9acc00-b59d-11e8-8807-cf3b42b64630.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
