### ISSUE TITLE
Problem with logos

### ISSUE THREAD

**Issue by ghost** [authenticatorplus/logos#169]
Good afternoon.
Logos that you added do not appear in the program itself and can not be selected manually. Also with the logo that you updated, they just disappeared. Example, for protonmail disappeared all the logo. 
The application deleted, cleared the data. There is nothing.

**Comment by MufriA** [comment]
There was case sensitive issue in protonmail it should show now, if some icon is not showing please update it here.

**Comment by ghost** [comment]
Icon is not show in the program. They only disappear from there.

**Comment by MufriA** [comment]
Which logo? all? what's your app version? phone version?

Are you able to view this link in your phone?

https://logos.authenticatorplus.com/ProtonMail.png

**Comment by ghost** [comment]
I do not see new logos, as well as old ones disappear if you update them. On the link the logo opens.

**Comment by ghost** [comment]
App version 3.8.8. My phone Leeco Le pro 3 and Galaxy 4.

**Comment by MufriA** [comment]
Could you try this, select an account, long press, press the image icon in toolbar and in the manual logo screen, tap the first option - Custom logo and select a logo from your phone, this will help me to find out if there is any issue with network or not

**Comment by ghost** [comment]
I selected the logo manually from my phone. What's next?

**Comment by ghost** [comment]
Logos available in the program [video](https://mega.nz/#F!RHhEhIzA!rxb7_Ky5PEhMFUF20CrvHw)
As you can see many logos are just missing.

**Comment by MufriA** [comment]
I can see in your video few logos like microsoft & Google are there, so then the issue could be that your service's logo is not there or not spelled correctly in the repo. If you can tell me the service name i can add it to the manual list you can manually select it from custom logos.

**Comment by ghost** [comment]
I thought in manual mode all logos are available for selection. Newly added protonmail and logo appeared.
But this one worked for HumbleBundle, the logo did not appear.

**Comment by MufriA** [comment]
Repo had Humble Bundle with space in it, looks they have changed it now without space, i have updated you should see the logo automatically.

**Comment by ghost** [comment]
Yes, the logo has appeared. Thank.
