### ISSUE TITLE
LDSAccount

### ISSUE THREAD

**Issue by psg190** [authenticatorplus/logos#17]
Please provide below info, all are mandatory

1. https://www.lds.org/?lang=eng (https://ident.lds.org/sso/UI/Login?service=credentials&goto=https%3a%2f%2fwww.lds.org%2fsigninout%2f%3flang%3deng)
2. **Exact Service Name** displayed in the app
LDSAccount
3. Upload the logo in 90x90, logo should be square
![ldsaccount](https://cloud.githubusercontent.com/assets/4184204/25770747/c29ff0f4-31f2-11e7-87b5-8dd91bbfec4b.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by psg190** [comment]
Had an error in the title of the service name on this one. It's actually LDS Account (no space) 

Once updated will Authenticator Plus automatically pull the 90x90 logo.?
