### ISSUE TITLE
Cloudways

### ISSUE THREAD

**Issue by TheGhostHybrid** [authenticatorplus/logos#170]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
**cloudways.com**
2. **Exact Service Name** displayed in the app
**Cloudways**
3. Upload the logo in 90x90, logo should be square
![cloudways-logo](https://user-images.githubusercontent.com/5500727/46123612-5a7a6b80-c1d4-11e8-97d6-376141df4ef0.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
