### ISSUE TITLE
Humble Bundle

### ISSUE THREAD

**Issue by TheGhostHybrid** [authenticatorplus/logos#171]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
**humblebundle.com**
2. **Exact Service Name** displayed in the app
**Humble Bundle**
3. Upload the logo in 90x90, logo should be square
![humble-bundle-logo](https://user-images.githubusercontent.com/5500727/46123789-32d7d300-c1d5-11e8-8bd2-677255cca693.png)

**Comment by MufriA** [comment]
We already have this in our db, please wait for the app to load or kill the app and open again.

Reopen the issue if still you couldn't see the logo.
