### ISSUE TITLE
reddit

### ISSUE THREAD

**Issue by TheGhostHybrid** [authenticatorplus/logos#172]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
**reddit.com**
2. **Exact Service Name** displayed in the app
**reddit**
3. Upload the logo in 90x90, logo should be square
![reddit-logo](https://user-images.githubusercontent.com/5500727/46123907-db863280-c1d5-11e8-86e6-e947b32d1314.png)

**Comment by KScheid** [comment]
this already exists

**Comment by EDIflyer** [comment]
> this already exists

Interesting - not showing as an option for me in the logo list - only ones beginning with an R are Rage4, RamNode, Razer Insider, RedHat.

**Comment by KScheid** [comment]
It should display automatically. There should be no need to manually choose
a icon.
If you click on closed issues in GitHub you should see that Reddit was
already submitted and approved.

**Comment by EDIflyer** [comment]
> It should display automatically. There should be no need to manually choose a icon. If you click on closed issues in GitHub you should see that Reddit was already submitted and approved.

Oh sure, I know they normally show automatically, but I thought the full list would also show when you went to pick manually.  I'm wondering if this is why things are sometimes getting re-requested? - if not showing up automatically then I thought the full suite of icons would appear in the manual list.  I know mufri has had some examples (e.g. Poloniex) where they've had to add them twice as they weren't showing up at first. Just trying to help suss out what's going on :)

**Comment by KScheid** [comment]
I have added lots of icons. Most of which don't show up in the list but
rather automatically appear. Actually I don't think any appear in the list

**Comment by EDIflyer** [comment]
Interesting - I wonder what determines whether they're automatic or in the manual list!

**Comment by MufriA** [comment]
If service name matches the logo in our repo it shows automatically, manual list is not synced with repo, its as of now updated only on request.
