### ISSUE TITLE
Square

### ISSUE THREAD

**Issue by TheGhostHybrid** [authenticatorplus/logos#173]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
**squareup.com**
2. **Exact Service Name** displayed in the app
**Square**
3. Upload the logo in 90x90, logo should be square
![square-logo](https://user-images.githubusercontent.com/5500727/46124090-daa1d080-c1d6-11e8-8d48-3687b6162f78.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
