### ISSUE TITLE
Zapier

### ISSUE THREAD

**Issue by TheGhostHybrid** [authenticatorplus/logos#174]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
**zapier.com**
2. **Exact Service Name** displayed in the app
**Zapier**
3. Upload the logo in 90x90, logo should be square
![zapier-logo](https://user-images.githubusercontent.com/5500727/46124147-38361d00-c1d7-11e8-99b0-90f33301be4a.png)

**Comment by MufriA** [comment]
We already have this in our db, please wait for the app to load or kill the app and open again.

Reopen the issue if still you couldn't see the logo.
