### ISSUE TITLE
Please add Bitwarden Logo

### ISSUE THREAD

**Issue by swjpilot** [authenticatorplus/logos#176]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
    https://bitwarden.com/
2. **Exact Service Name** displayed in the app
    Bitwarden
3. Upload the logo in 90x90, logo should be square
![bitwarden_logo](https://user-images.githubusercontent.com/29280467/46493618-dda44e80-c7de-11e8-9268-4db28e5420a4.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
