### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#177]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
Instagram.com
2. **Exact Service Name** displayed in the app
Instagram
3. Upload the logo in 90x90, logo should be square
![instagram90](https://user-images.githubusercontent.com/25370801/46961544-3933cf00-d05e-11e8-84fa-e5df561f9c6a.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
