### ISSUE TITLE
PriusChat

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#178]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://priuschat.com/forum/
2. **Exact Service Name** displayed in the app
PriusChat
3. Upload the logo in 90x90, logo should be square
![priuschat90](https://user-images.githubusercontent.com/25370801/46962140-9da35e00-d05f-11e8-9e3b-489312277b95.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
