### ISSUE TITLE
Robinhood

### ISSUE THREAD

**Issue by gio-vanni** [authenticatorplus/logos#179]
1. Website URL of server, even twitter page of the service too is fine
https://www.robinhood.com/

2. **Exact Service Name** displayed in the app
Robinhood

3. Upload the logo in 90x90, logo should be square
![robinhood_logo](https://user-images.githubusercontent.com/41984681/47206628-1bfd4a00-d357-11e8-8031-6376aa697b88.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
