### ISSUE TITLE
Jeedom

### ISSUE THREAD

**Issue by DamienLGD** [authenticatorplus/logos#18]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.jeedom.com/site/fr/

2. **Exact Service Name** displayed in the app
Jeedom

3. Upload the logo in 90x90, logo should be square
![jeedom](https://cloud.githubusercontent.com/assets/19608131/26033211/9385a3de-38a7-11e7-8f14-22c56f282e18.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
