### ISSUE TITLE
*** ADOBE logo missing/never available/please add ***

### ISSUE THREAD

**Issue by curtismorrison** [authenticatorplus/logos#180]
Adobe #130 requested this logo earlier this year/request is closed/said logo is there, but it is not at least in in iOS app...

1)  URL: adobe.com

2)  Service Name: Adobe

3)  Image uploaded/attached: Adobe.png

![adobe](https://user-images.githubusercontent.com/44311293/47251910-b49bd480-d400-11e8-88e5-d53d7d5f7cf6.png)

**Comment by EDIflyer** [comment]
It's not there in Android either - would be fantastic to get it added, only one I'm missing just now! #OCD

**Comment by MufriA** [comment]
Issue is service name of adobe is **Adobe Id** not just **Adobe**, just verified its working now, please confirm

**Comment by EDIflyer** [comment]
Confirm now working, thanks!

**Comment by curtismorrison** [comment]
It's not in the list of available logos when I edit the existing Adobe entry. Trick to refresh this?
