### ISSUE TITLE
New Icon Request -- FastMail

### ISSUE THREAD

**Issue by jpgbkugahvuzidxehcnm** [authenticatorplus/logos#181]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.fastmail.com/

2. **Exact Service Name** displayed in the app
FastMail

3. Upload the logo in 90x90, logo should be square
![fastmail logo](https://user-images.githubusercontent.com/17951134/47255641-80e19e80-d442-11e8-8c3a-4a067ff98b0d.png)

**Comment by MufriA** [comment]
We already have this in our db, please wait for the app to load or kill the app and open again.

Reopen the issue if still you couldn't see the logo.
