### ISSUE TITLE
New Icon Request -- UN FCU

### ISSUE THREAD

**Issue by jpgbkugahvuzidxehcnm** [authenticatorplus/logos#182]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.unfcu.org/

2. **Exact Service Name** displayed in the app
UN FCU

3. Upload the logo in 90x90, logo should be square
![un fcu icon](https://user-images.githubusercontent.com/17951134/47255722-7378e400-d443-11e8-8ca3-bf837bff0a87.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
