### ISSUE TITLE
New Icon Request -- Sourceforge

### ISSUE THREAD

**Issue by jpgbkugahvuzidxehcnm** [authenticatorplus/logos#183]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.sourceforge.net/

2. **Exact Service Name** displayed in the app
Sourceforge

3. Upload the logo in 90x90, logo should be square
![sourceforge icon](https://user-images.githubusercontent.com/17951134/47255828-7c1dea00-d444-11e8-8ce0-90a1efe3b72d.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
