### ISSUE TITLE
Real VNC Logo Request

### ISSUE THREAD

**Issue by jwhaleyca** [authenticatorplus/logos#184]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
2. **Exact Service Name** displayed in the app
3. Upload the logo in 90x90, logo should be square

https://www.realvnc.com/en/
Real VNC
![512x512bb](https://user-images.githubusercontent.com/34733145/47338876-48aeab80-d64e-11e8-8f63-b15577941332.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
