### ISSUE TITLE
Microsoft Logo Request

### ISSUE THREAD

**Issue by jwhaleyca** [authenticatorplus/logos#185]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
2. **Exact Service Name** displayed in the app
3. Upload the logo in 90x90, logo should be square

https://login.live.com/login.srf
Microsoft
![2000px-microsoft_logo svg](https://user-images.githubusercontent.com/34733145/47338952-81e71b80-d64e-11e8-97ff-a900184549fe.png)

**Comment by EDIflyer** [comment]
This is already showing up in the app for me as an option?

**Comment by jpgbkugahvuzidxehcnm** [comment]
It shows for me too.

**Comment by jwhaleyca** [comment]
I just see the Android logo

**Comment by MufriA** [comment]
We already have this in our db, please wait for the app to load or kill the app and open again.

Reopen the issue if still you couldn't see the logo.
