### ISSUE TITLE
Bahamut Logo Request

### ISSUE THREAD

**Issue by eclipse999** [authenticatorplus/logos#186]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.gamer.com.tw
2. **Exact Service Name** displayed in the app
Bahamut
3. Upload the logo in 90x90, logo should be square
![bahamut](https://user-images.githubusercontent.com/44665823/47841284-117d8e80-ddf4-11e8-8160-951d7395bf35.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by maple3142** [comment]
@MufriA When will the in-app icon list update?

**Comment by MufriA** [comment]
Do you mean manual list? it will be updated only when there is any change, your logo should automatically load if the service name is **exactly** same
