### ISSUE TITLE
Uplay

### ISSUE THREAD

**Issue by Ali1383H** [authenticatorplus/logos#187]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://uplay.ubi.com/
2. **Exact Service Name** displayed in the app
Uplay
3. Upload the logo in 90x90, logo should be square
![uplay](https://user-images.githubusercontent.com/44734688/47957240-f315bf80-dfba-11e8-990e-3672a466e226.png)

**Comment by MufriA** [comment]
Updated the logo, thanks.
