### ISSUE TITLE
ProtonMail

### ISSUE THREAD

**Issue by Ali1383H** [authenticatorplus/logos#188]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://protonmail.com/
2. **Exact Service Name** displayed in the app
ProtonMail
3. Upload the logo in 90x90, logo should be square
![protonmail](https://user-images.githubusercontent.com/44734688/47957269-4be55800-dfbb-11e8-9a13-258b66cd19af.png)

**Comment by KScheid** [comment]
this one has already been submitted and merged look at #168[](https://github.com/authenticatorplus/logos/issues/168)

**Comment by MufriA** [comment]
We already have this in our db, please wait for the app to load or kill the app and open again.

Reopen the issue if still you couldn't see the logo.
