### ISSUE TITLE
Paymium

### ISSUE THREAD

**Issue by Lantizia** [authenticatorplus/logos#19]
1. paymium.com

2. Paymium

^^ HOWEVER: An otpauth:// example (yes it's pre-censored) shows they're using +-+ instead of : to delimit between service name and username (which is the BC-U12345678 part).  If Paymium are doing this wrong then let me know and I'll let them know (as a customer I can log tickets).

e.g.  otpauth://totp/Paymium+-+BC-U12345678?secret=abcdefghijklmn12&digits=6   

3. Two possible logos both in 90x90 format (the PAY is their favicon and the other is just their logo).

![paymium](https://cloud.githubusercontent.com/assets/10448369/26211529/885e0e1a-3bea-11e7-99a0-c0544e8f7bec.png)
![paymium icon](https://cloud.githubusercontent.com/assets/10448369/26211530/88754210-3bea-11e7-9bde-225c19143759.png)

Actually looking at the app it seems there is a Paymium icon, perhaps it isn't matching to the service name "Paymium" automatically? (which is what is delivered via QR code on their site)  possibly because of their +-+ bug?

**Comment by MufriA** [comment]
Yes their format is wrong, refer https://github.com/google/google-authenticator/wiki/Key-Uri-Format

For now, you can long press the account and pick the logo from list, this will set the logo.

**Comment by Lantizia** [comment]
Is there a way of changing service names? (so I can fix their +-+ issue manually)... the only way I can think to do this at the moment would be to export all the oath strings, edit them and re-import them?
