### ISSUE TITLE
Adobe

### ISSUE THREAD

**Issue by kentiongson** [authenticatorplus/logos#190]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
2. **Exact Service Name** displayed in the app
3. Upload the logo in 90x90, logo should be square

**Comment by EDIflyer** [comment]
See bug #180 ;) (or indeed #130 :D)

**Comment by MufriA** [comment]
Issue is service name of adobe is **Adobe Id** not just **Adobe**, just verified its working now, please confirm
