### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by kentiongson** [authenticatorplus/logos#191]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
2. **Exact Service Name** displayed in the app
3. Upload the logo in 90x90, logo should be square

**Comment by jelbo** [comment]
1. https://www.instagram.com/
2. Instagram
3. ![instagram 90x90](https://user-images.githubusercontent.com/7387027/48190701-a5df7800-e343-11e8-83a9-b0cb6be3b6b4.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
