### ISSUE TITLE
Buildkite

### ISSUE THREAD

**Issue by mateusz-bajorek** [authenticatorplus/logos#193]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://buildkite.com/
2. **Exact Service Name** displayed in the app
Buildkite
3. Upload the logo in 90x90, logo should be square
![buildkite](https://user-images.githubusercontent.com/11185738/48841075-a5f26580-ed90-11e8-9454-65ece59c24cb.png)

**Comment by RobeeeJay** [comment]
+1!

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
