### ISSUE TITLE
Private Internet Access

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#194]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.privateinternetaccess.com/
2. **Exact Service Name** displayed in the app
Private Internet Access - [username]
3. Upload the logo in 90x90, logo should be square
![pia90](https://user-images.githubusercontent.com/25370801/50298264-f5818b00-043b-11e9-9556-dcf2e71b98d8.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
