### ISSUE TITLE
DocuSign logo

### ISSUE THREAD

**Issue by ixtlanian** [authenticatorplus/logos#195]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.docusign.com/
2. **Exact Service Name** displayed in the app
DocuSign
3. Upload the logo in 90x90, logo should be square
DocuSign logo is very rectangular and will not make any sense in square form factor. The proposed icon is what they use as their website favicon as well as icon for their service in many places requiring square format.
![dosusign icon 90x90](https://user-images.githubusercontent.com/46237184/50534469-19fbf800-0b0b-11e9-8b17-bc722b3aaf7b.png)

**Comment by MufriA** [comment]
Makes sense, I have replaced this, see if this is getting downloaded.

**Comment by ixtlanian** [comment]
Tried clearing the cache, but no DocuSign in the list of logos on the app.

**Comment by MufriA** [comment]
Then most likely there's some issue DocuSign service name can you double confirm the spelling.

**Comment by ixtlanian** [comment]
Correct - DocuSign is not the full service name. They have some meaningless stuff like DocuSign (NA3-EU1) and the items in parenthesis will change depending on the site. So, I can see why the icon does not get associated automatically. So, unless you allow wildcard service names, where you could define it as DocuSign*, this one will be impossible to match as there will never be the exact match.
However, that's not the issue. The issue is that when I try to assign the icon manually, DocuSign icon is not among the list of services even after clearing the app cache.
I am on the beta group if that makes the difference, but somehow this logo did not make its way into the app.
