### ISSUE TITLE
Rockstar Games

### ISSUE THREAD

**Issue by KScheid** [authenticatorplus/logos#196]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
rockstargames.com
2. **Exact Service Name** displayed in the app
Rockstar+Games:[email address]
3. Upload the logo in 90x90, logo should be square
![rockstar90](https://user-images.githubusercontent.com/25370801/50604404-10acbb80-0e7c-11e9-8cf9-955dfeff6017.png)

**Comment by MufriA** [comment]
I have included the requested icon, long press your account row, click logo button from toolbar and wait for icons to load till spinner goes off, select your service from the list.
