### ISSUE TITLE
Solidi

### ISSUE THREAD

**Issue by Lantizia** [authenticatorplus/logos#20]
1. solidi.co

2. Solidi Ltd

3. Two possible logos both in 90x90 format (the S is their favicon and the other is just their logo).

![solidi](https://cloud.githubusercontent.com/assets/10448369/26211630/d628af56-3bea-11e7-83a8-1155117697f1.png)
![solidi icon](https://cloud.githubusercontent.com/assets/10448369/26211629/d626b69c-3bea-11e7-920b-82647a362d1a.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by Lantizia** [comment]
Works great thanks
