### ISSUE TITLE
Greenview Data

### ISSUE THREAD

**Issue by kongo09** [authenticatorplus/logos#203]
https://www.greenviewdata.com/
Greenview Data, Inc.
![gd](https://user-images.githubusercontent.com/640121/51444631-4c5bd800-1cfa-11e9-890b-b73a44b3f143.png)

**Comment by MufriA** [comment]
I have included the requested icon, long press your account row, click logo button from toolbar and wait for icons to load till spinner goes off, select your service from the list.
