### ISSUE TITLE
Jumplead

### ISSUE THREAD

**Issue by adamlc** [authenticatorplus/logos#204]
1. https://jumplead.com
2. Jumplead
3.
![jumplead](https://user-images.githubusercontent.com/809944/51967776-2526a880-2468-11e9-9629-02538d86afde.png)

**Comment by adamlc** [comment]
Or a logo with a transparent background if preferred:

![logo](https://user-images.githubusercontent.com/809944/51968196-3fad5180-2469-11e9-9ebf-a5331d9b1bf7.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
