### ISSUE TITLE
Uber

### ISSUE THREAD

**Issue by ixtlanian** [authenticatorplus/logos#206]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
www.uber.com
2. **Exact Service Name** displayed in the app
Uber - [FirstName LastName]
Please also make it available in the library for manual selection.
3. Upload the logo in 90x90, logo should be square
![uber](https://user-images.githubusercontent.com/46237184/52187723-24419e00-27fd-11e9-97a2-31250f89c11d.png)

**Comment by MufriA** [comment]
I have included the requested icon, long press your account row, click logo button from toolbar and wait for icons to load till spinner goes off, select your service from the list.
