### ISSUE TITLE
Pritunl

### ISSUE THREAD

**Issue by sj-louw** [authenticatorplus/logos#207]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://twitter.com/pritunl

2. **Exact Service Name** displayed in the app
Pritunl

3. Upload the logo in 90x90, logo should be square
![pritunl](https://user-images.githubusercontent.com/29563018/54481655-26f1d300-4840-11e9-9de0-076b196683db.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
