### ISSUE TITLE
Cisco

### ISSUE THREAD

**Issue by sj-louw** [authenticatorplus/logos#208]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://twitter.com/Cisco

2. **Exact Service Name** displayed in the app
CiscoOneIdentity

3. Upload the logo in 90x90, logo should be square
![cisco](https://user-images.githubusercontent.com/29563018/54481689-9ebffd80-4840-11e9-9e52-edba63abce42.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
