### ISSUE TITLE
Atlassian

### ISSUE THREAD

**Issue by sj-louw** [authenticatorplus/logos#209]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://twitter.com/atlassian

2. **Exact Service Name** displayed in the app
Atlassian

3. Upload the logo in 90x90, logo should be square
![atlassian](https://user-images.githubusercontent.com/29563018/54481699-cd3dd880-4840-11e9-824b-fff971a8174e.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by RedSpeeds** [comment]
Reopening as logo seems to not be present in the logo database on the actual app
