### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by Lantizia** [authenticatorplus/logos#21]
1. blockchain.info
2. blockchain.info
3. The symbol from their favicon in 90x90...

![blockchain icon](https://cloud.githubusercontent.com/assets/10448369/26213500/358a27ee-3bf1-11e7-971d-b4026a8b2b73.png)

It seems the above is their new official logo...
https://blog.blockchain.com/2017/01/13/our-legacy-and-a-new-logo/

They also seem to have become "Blockchain" rather than "Blockchain.info" as an official name.

Looking at your full list of logos in the app... "Blockchain.info" is listed with an out of date icon I think... perhaps the app doesn't know to check for service name "blockchain.info" which is what was delivered via their QR code on the site (case sensitive also maybe?).

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by Lantizia** [comment]
The other logos you've recently added work - but this one doesn't.

Did you update the existing logo you had to this one... but then leave the service name the way it was?  because they're handing out "blockchain.info" on their website (inside the QR) despite now simply calling themselves Blockchain.

**Comment by Lantizia** [comment]
Hi I don't think this has been merged properly... none of these strings work for finding the logo automatically...

Blockchain
BlockChain
blockchain.info (their website QR code uses this one)
blockchain.com
Block Chain

In the end I used Blockchain.info (with a capital B) which just got me to old blue square B type logo and not the one I've submitted above.

**Comment by MufriA** [comment]
Some upload error, try now it should work, thanks for reproting

**Comment by Lantizia** [comment]
Sorry no this still doesn't work...

Issuer "Blockchain.info" still gives the old logo
Issuer "blockchain.info" (which it should be, as that's what the website QR gives out) gives no logo at all.

**Comment by MufriA** [comment]
for some reason files with two dots is not working as expected, for now i have added blockchain as custom icon, long press the account and pick it from list of icons.
