### ISSUE TITLE
Carbonite

### ISSUE THREAD

**Issue by sj-louw** [authenticatorplus/logos#210]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://carbonite.co.za

2. **Exact Service Name** displayed in the app
Carbonite

3. Upload the logo in 90x90, logo should be square
![carbonite](https://user-images.githubusercontent.com/29563018/54481711-08d8a280-4841-11e9-945d-fb79f51dcc51.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
