### ISSUE TITLE
Miningpoolhub

### ISSUE THREAD

**Issue by sj-louw** [authenticatorplus/logos#211]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://miningpoolhub.com

2. **Exact Service Name** displayed in the app
Miningpoolhub

3. Upload the logo in 90x90, logo should be square
![miningpoolhub](https://user-images.githubusercontent.com/29563018/54481734-4f2e0180-4841-11e9-9778-97e2caa93ae9.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
