### ISSUE TITLE
mailbox.org

### ISSUE THREAD

**Issue by st167** [authenticatorplus/logos#212]
Logo request:
Please provide below info, all are mandatory

1. URL: https://mailbox.org/en/
2. Display: Mailbox.org
3. Sample logo attached.
![logo](https://user-images.githubusercontent.com/23350116/54536118-79c5aa80-4966-11e9-8b7c-f0747d1fa3cd.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
