### ISSUE TITLE
Add the ability for users to upload logos

### ISSUE THREAD

**Issue by elieobeid7** [authenticatorplus/logos#217]
I work for multiple clients, I install 2FA on all websites I work on. It's not cool to come here, say hey here's my client's website, please add a logo.

Please add the ability for users to change the logo on their own phones. It doesn't have to be stored online. Logos can be stored on the mobile phone of users locally.

**Comment by h13Bishop** [comment]
There is an option to add your custom logo to every key.

The other problem is that when you add custom logo the file is not added to database. So when you remove the program for example and then restore from backup custom logos will not show.

**Comment by elieobeid7** [comment]
> There is an option to add your custom logo to every key.

How to do that? Couldn't find the option.

> The other problem is that when you add custom logo the file is not added to database. So when you remove the program for example and then restore from backup custom logos will not show.

It's alright, no big deal

**Comment by elieobeid7** [comment]
Found it thank you!!
