### ISSUE TITLE
FireBrick

### ISSUE THREAD

**Issue by Lantizia** [authenticatorplus/logos#22]
1. firebrick.co.uk (but actually it's not for their website its for the network appliances they make)
2. FireBrick
3. Logo in 90x90...

![firebrick](https://cloud.githubusercontent.com/assets/10448369/26236215/2d04103c-3c67-11e7-80fb-d0fb8766a74f.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by Lantizia** [comment]
Thanks working great :)
