### ISSUE TITLE
PayPal

### ISSUE THREAD

**Issue by Lantizia** [authenticatorplus/logos#23]
Stay with me here, it does actually work :)

1. paypal.com / paypal.co.uk / etc...
2. Complicated :) see below for the otpauth:// generated in the screenshot (but it's not PayPal specific)
3. Logo...

![paypal](https://cloud.githubusercontent.com/assets/10448369/26296245/b8d8dcf4-3ec5-11e7-91c9-48c0d2e6bed7.png)

Here is ***how*** (as this might be a method you'd want to build in to the app)...

Get this little Python app that generates a VIP Access serial...

https://github.com/zecoj/python-vipaccess (this is a temporary fork of https://github.com/cyrozap/python-vipaccess)

Then simply add it to PayPal on this page...
https://www.paypal.com/us/cgi-bin/webscr?cmd=_activate-security-key-any

An ***EXAMPLE*** (it's been pre-censored) of this being done is below...

![paypal example](https://cloud.githubusercontent.com/assets/10448369/26296308/0acd1e26-3ec6-11e7-9d0e-8e5cecd31c5d.png)

For more information on how the VIP Access serials are generated see this blog post...
https://www.cyrozap.com/2014/09/29/reversing-the-symantec-vip-access-provisioning-protocol/

It seems these VIP Access serials work with numerous sites, see... https://idprotect.vip.symantec.com/wheretouse.v

Unfortunately (I think because eBay and PayPal split... and eBay was just *borrowing* the ability use them from PayPal since then) I think they don't work with eBay any more (as you'd activate them at this link which doesn't work any more... https://signin.ebay.co.uk/ws/eBayISAPI.dll?ActivateSecurityToken), see also... https://krebsonsecurity.com/2017/03/ebay-asks-users-to-downgrade-security/

**Comment by MufriA** [comment]
Thanks for steps, this will help others, the github site you have mentioned is using reverse engineered approach to generate QR code, I have stopped adding these workarounds in app because it cause more confusion then solving.

**Comment by MufriA** [comment]
I have updated logo to the new one.

**Comment by Lantizia** [comment]
When you say you've updated the logo to the new one... which string does the service name have to be in order to match it with that logo?

Also is the only way of changing service names... is to export all your oath strings, edit them and re-import them?  Is there anyway to edit a service name directly in the app (which would help for broken strings like Paymium and also non-specific strings like the Symantec/VIP Access/PayPal one)

**Comment by Lantizia** [comment]
Yeah confirmed - if I manually export the oath string... edit it so the Issuer is just 'PayPal' then pass it back into the app - then the logo shows up.

It'd be nice to have a feature to edit the issue names or just edit the oath strings in-app I suppose.

**Comment by Caligatio** [comment]
Did this disappear?  I can't find it in the services list.
