### ISSUE TITLE
Extract

### ISSUE THREAD

**Issue by GBR963** [authenticatorplus/logos#233]
Authenticator Plus:
Extract as Text and HTML isn't working correctly.
The extracted zipped files can't be opened by a file manager or zip viewer, neither on windows 10 nor on android.

Authenticator Plus Version 3.8.8
Android Version 7.0

![Annotation 2019-10-05 135240](https://user-images.githubusercontent.com/56193283/66254531-bf698980-e777-11e9-89fd-999fff83ad8e.jpg)

**Comment by MufriA** [comment]
Zip is password protected, you can use any app which supports, I don't use windows but typically winzip or winrar works.

I just tried this app in Android, it works too 

https://play.google.com/store/apps/details?id=com.rarlab.rar
