### ISSUE TITLE
GratisDNS

### ISSUE THREAD

**Issue by ragnars-stuff** [authenticatorplus/logos#24]
Please provide below info, all are mandatory

1. https://web.gratisdns.dk/
2. GratisDNS
3. Upload the logo in 90x90, logo should be square
![gratis_theme_logo](https://cloud.githubusercontent.com/assets/195335/26349343/58aadbd8-3fa7-11e7-8135-fde9104fef02.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
