### ISSUE TITLE
Update CurrencyFair icon

### ISSUE THREAD

**Issue by mateusz-bajorek** [authenticatorplus/logos#29]
1. Website URL of server, even twitter page of the service too is fine
www.currencyfair.com   https://twitter.com/CurrencyFair
2. **Exact Service Name** displayed in the app
CurrencyFair
3. Upload the logo in 90x90, logo should be square
![img_20170610_121946](https://user-images.githubusercontent.com/11185738/27002012-43de33ce-4dd7-11e7-8fba-f8f808c00d52.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
