### ISSUE TITLE
Sync Logo

### ISSUE THREAD

**Issue by ghost** [authenticatorplus/logos#3]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://bitwarden.com/

2. **Exact Service Name** displayed in the app
Sync

3. Upload the logo in 90x90, logo should be square
![sync](https://cloud.githubusercontent.com/assets/26840098/24579888/41a4f6ac-16cc-11e7-88f1-0cf44ecb4355.png)

**Comment by MufriA** [comment]
Website name and service name is not matching, am i missing something?

**Comment by MufriA** [comment]
You have already requested different logo for the same website in #4

**Comment by ghost** [comment]
Sorry, the website should be sync.com.

**Comment by MufriA** [comment]
Done, uploaded.
