### ISSUE TITLE
GoDaddy Logo

### ISSUE THREAD

**Issue by sjlouw** [authenticatorplus/logos#30]
1. Website URL of server, even twitter page of the service too is fine:
https://godaddy.com
https://twitter.com/GoDaddy

2. **Exact Service Name** displayed in the app
GoDaddy

3. Upload the logo in 90x90, logo should be square
![lbonkg5g_400x400](https://user-images.githubusercontent.com/2770588/27009663-53d85134-4e94-11e7-9346-78467a41e404.jpeg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
