### ISSUE TITLE
Luno Logo

### ISSUE THREAD

**Issue by sjlouw** [authenticatorplus/logos#31]
1. Website URL of server, even twitter page of the service too is fine
https://www.luno.com
https://twitter.com/lunomoney

2. **Exact Service Name** displayed in the app
Luno

3. Upload the logo in 90x90, logo should be square
![e2i8vv45_400x400](https://user-images.githubusercontent.com/2770588/27009683-aa123ee8-4e94-11e7-947a-b30418776d56.jpeg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
