### ISSUE TITLE
NiceHash Logo

### ISSUE THREAD

**Issue by sjlouw** [authenticatorplus/logos#32]
1. Website URL of server, even twitter page of the service too is fine
https://www.nicehash.com
https://twitter.com/NiceHashMining

2. **Exact Service Name** displayed in the app
NiceHash

3. Upload the logo in 90x90, logo should be square
![epnjvjxe_400x400](https://user-images.githubusercontent.com/2770588/27009698-199b72f2-4e95-11e7-82ed-adfb64d966d4.jpeg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
