### ISSUE TITLE
GoDaddy Logo **Update**

### ISSUE THREAD

**Issue by sjlouw** [authenticatorplus/logos#33]
**Transparent png with rounded corners.

Website URL of server, even twitter page of the service too is fine:
https://godaddy.com
https://twitter.com/GoDaddy

Exact Service Name displayed in the app
GoDaddy

Upload the logo in 90x90, logo should be square
![godaddy](https://user-images.githubusercontent.com/2770588/27026633-b4e85170-4f5e-11e7-85ac-6377a151a067.png)

**Comment by MufriA** [comment]
Thanks for the updated icon.
