### ISSUE TITLE
Luno Icon **Update**

### ISSUE THREAD

**Issue by sjlouw** [authenticatorplus/logos#34]
**Transparent png with rounded corners.

Website URL of server, even twitter page of the service too is fine
https://www.luno.com
https://twitter.com/lunomoney

Exact Service Name displayed in the app
Luno

Upload the logo in 90x90, logo should be square
![luno](https://user-images.githubusercontent.com/2770588/27026682-e29fdaac-4f5e-11e7-8a7e-713442d49df5.png)

**Comment by MufriA** [comment]
Thanks for the updated icon.
