### ISSUE TITLE
NiceHash Logo **Update**

### ISSUE THREAD

**Issue by sjlouw** [authenticatorplus/logos#35]
**Transparent png with rounded corners.

Website URL of server, even twitter page of the service too is fine
https://www.nicehash.com
https://twitter.com/NiceHashMining

Exact Service Name displayed in the app
NiceHash

Upload the logo in 90x90, logo should be square
![nicehash](https://user-images.githubusercontent.com/2770588/27026724-06fe8e0c-4f5f-11e7-8938-19ff8a7f918b.png)

**Comment by MufriA** [comment]
Thanks for the updated icon.
