### ISSUE TITLE
Mineplex Logo

### ISSUE THREAD

**Issue by ArcticZeroo** [authenticatorplus/logos#36]
1. Website URL of server, even twitter page of the service too is fine
http://mineplex.com
2. **Exact Service Name** displayed in the app
Mineplex
Mineplex Test
3. Upload the logo in 90x90, logo should be square
![mineplex-m-small](https://user-images.githubusercontent.com/5075030/27253406-0870da42-5342-11e7-9053-a859420c7d47.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
