### ISSUE TITLE
Snapchat Logo

### ISSUE THREAD

**Issue by ArcticZeroo** [authenticatorplus/logos#37]
1. Website URL of server, even twitter page of the service too is fine
https://www.snapchat.com/
2. **Exact Service Name** displayed in the app
Snapchat
3. Upload the logo in 90x90, logo should be square
![snapchat-small](https://user-images.githubusercontent.com/5075030/27253416-49e735e8-5342-11e7-843d-1e1b5fc386f7.png)

**Comment by ArcticZeroo** [comment]
I just saw #1 where it was closed as "Already Available", but in my (fully updated) app, there's no Snapchat. It goes Slack, Slush Pool, then SoftLayer. I've scrolled through multiple times and it's not anywhere in the list.

edit: Actually missing all the logos I checked that were merged... odd

**Comment by MufriA** [comment]
Just verified Snapchat is there, can you verify again with different network.

**Comment by ArcticZeroo** [comment]
@MufriA is it supposed to show up in the icons menu? The Mineplex logo (#36) automatically synced and updated when I opened the app, but I don't see it in the icons list. Snapchat did not automatically update.

**Comment by ragnars-stuff** [comment]
Snapchat logo is not showing up for me.

Did a fresh install of oAndroind and app on Monday
