### ISSUE TITLE
Andrews & Arnold Ltd

### ISSUE THREAD

**Issue by Lantizia** [authenticatorplus/logos#39]
1. aa.net.uk
2. Andrews & Arnold Ltd
3. ![aa](https://user-images.githubusercontent.com/10448369/27279311-2c94a43a-54dc-11e7-86d3-5a84e63dc8c4.png)

**Comment by MufriA** [comment]
Added icon, it has special chars in name, let me know if it works.

**Comment by Lantizia** [comment]
Yes that's worked fine - thanks :)
