### ISSUE TITLE
Bitwarden Logo

### ISSUE THREAD

**Issue by ghost** [authenticatorplus/logos#4]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://bitwarden.com/

2. **Exact Service Name** displayed in the app
bitwarden

3. Upload the logo in 90x90, logo should be square
![bitwarden](https://cloud.githubusercontent.com/assets/26840098/24579899/7124fe18-16cc-11e7-980d-b5e94fcc2f86.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by kongo09** [comment]
Bitwarden Logo does not show in AuthenticatorPlus on Android. It is also not part of the logo list.

**Comment by WattvilleBlues** [comment]
Any progress on this?
