### ISSUE TITLE
Poloniex

### ISSUE THREAD

**Issue by ManiusNG** [authenticatorplus/logos#43]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://poloniex.com
2. **Exact Service Name** displayed in the app
Poloniex
3. Upload the logo in 90x90, logo should be square
![poloniex](https://user-images.githubusercontent.com/29511496/27691983-dc68fee0-5ce5-11e7-8126-41592fa6f37f.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
