### ISSUE TITLE
BitBay

### ISSUE THREAD

**Issue by ManiusNG** [authenticatorplus/logos#44]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://bitbay.net/
2. **Exact Service Name** displayed in the app
BitBay
3. Upload the logo in 90x90, logo should be square
![bitbay](https://user-images.githubusercontent.com/29511496/27692034-f63f925c-5ce5-11e7-84ac-640715ff3cf3.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
