### ISSUE TITLE
Kickstarter

### ISSUE THREAD

**Issue by ManiusNG** [authenticatorplus/logos#45]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.kickstarter.com/
2. **Exact Service Name** displayed in the app
Kickstarter
3. Upload the logo in 90x90, logo should be square
![kickstarter](https://user-images.githubusercontent.com/29511496/27692099-266045e4-5ce6-11e7-9d6d-4013d69952a6.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
