### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by ghost** [authenticatorplus/logos#46]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
2. **Exact Service Name** displayed in the app
3. Upload the logo in 90x90, logo should be square

**Comment by ghost** [comment]
1. https://blockchain.info/wallet/#/
2. blockchain.info
![unnamed](https://user-images.githubusercontent.com/30007892/27988591-8267008a-6425-11e7-94f4-b1c4869eb3f2.png)

**Comment by ghost** [comment]
3. 90x90 logo
![90x90 logo](https://user-images.githubusercontent.com/30007892/27988604-d7dd85b6-6425-11e7-8175-a45b34d1bc16.png)

**Comment by ghost** [comment]
No answer...??

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
