### ISSUE TITLE
Uplay

### ISSUE THREAD

**Issue by ManiusNG** [authenticatorplus/logos#49]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://uplay.ubi.com/
2. **Exact Service Name** displayed in the app
Uplay
3. Upload the logo in 90x90, logo should be square
![uplay_logo](https://user-images.githubusercontent.com/29511496/29006325-cca8ae26-7aed-11e7-8b4d-c7bffeec737a.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
