### ISSUE TITLE
Snapshat Logo

### ISSUE THREAD

**Issue by theo-ger** [authenticatorplus/logos#5]
https://www.snapchat.com

Snapchat

![snapchat-logo](https://cloud.githubusercontent.com/assets/13695693/24657113/5d2801a0-1945-11e7-9ae2-91c1f25add1e.png)

------------------------------------------------

In closed topics, it is marked that Snapchat is already added while it is not in the list.

![screen](https://cloud.githubusercontent.com/assets/13695693/24657999/a89a090a-1948-11e7-9752-db19f45b7975.png)

**Comment by MufriA** [comment]
Its available already, it will automatically load ... is it not loading?

**Comment by theo-ger** [comment]
No, the logo does not load and is not in the "Define a logo" list (above).  (Sorry for bad translation)

**Comment by MufriA** [comment]
Just now I have enabled 2 factor auth in snapchat and it worked, not sure what's the issue for you.

Can you try to click the link in your mobile and see if it opens snapchat logo in browser

https://logos.authenticatorplus.com/Snapchat.png

Is it possible some blocking is happening, not sure how other logos are loaded.
