### ISSUE TITLE
Kraken

### ISSUE THREAD

**Issue by wernight** [authenticatorplus/logos#50]
Website URL: http://www.kraken.com/
Name: `Kraken` is their name but what do you mean "in the app"? It's shown as `Kraken XXXX` when XXXX is a code.

![image](https://user-images.githubusercontent.com/145667/29356464-af179c76-8274-11e7-932d-ed512cf8b9aa.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
