### ISSUE TITLE
Spectrocoin

### ISSUE THREAD

**Issue by wernight** [authenticatorplus/logos#51]
Website URL: https://spectrocoin.com
Name: Shown as `Spectrocoin.com` (but just `SpectroCoin` is also ok, yes casing like that)

![image](https://user-images.githubusercontent.com/145667/29356729-7bac5ac4-8275-11e7-877d-e6a3244b11b1.png)

**Comment by wernight** [comment]
Alternative logo:
![image](https://user-images.githubusercontent.com/145667/29356777-a56f29b8-8275-11e7-9276-605956665c3f.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
