### ISSUE TITLE
Coinbase (wrong logo)

### ISSUE THREAD

**Issue by wernight** [authenticatorplus/logos#52]
Website: https://www.coinbase.com/
Name: Not sure. It's called `Coinbase` but shows my email in Auth+.

Issue: Current logo doesn't match at all.

Should be one of:
![image](https://user-images.githubusercontent.com/145667/29357103-af801880-8276-11e7-8971-be4a85fb1cc9.png)
![image](https://user-images.githubusercontent.com/145667/29357189-f2e196e4-8276-11e7-927a-1e06dccdb2fc.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
