### ISSUE TITLE
Mastodon logo

### ISSUE THREAD

**Issue by justinkelly** [authenticatorplus/logos#53]
1. Website URL of server, even twitter page of the service too is fine

* https://mastodon.social
* https://joinmastodon.org/

2. **Exact Service Name** displayed in the app

Mastodon

3. Upload the logo in 90x90, logo should be square

logos available in branding pack: https://joinmastodon.org/press-kit.zip

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
