### ISSUE TITLE
Prey Project Logo

### ISSUE THREAD

**Issue by justinkelly** [authenticatorplus/logos#54]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine

preyproject.com

2. **Exact Service Name** displayed in the app

Prey Project 

3. Upload the logo in 90x90, logo should be square

https://www.preyproject.com/hubfs/new/images/logo.svg

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
