### ISSUE TITLE
Uplay

### ISSUE THREAD

**Issue by ManiusNG** [authenticatorplus/logos#55]
Please provide below info, all are mandatory

Website URL of server, even twitter page of the service too is fine
https://uplay.ubi.com/
Exact Service Name displayed in the app
Uplay
Upload the logo in 90x90, logo should be square
![uplay_logo](https://user-images.githubusercontent.com/29511496/29536388-e67be030-86bd-11e7-8cd8-075df78c85fd.png)

**Comment by MufriA** [comment]
its works fine, in two of my devices, is service name you have mentioned in the issue is correct ?, it should be EXACTLY CORRECT to work.

**Comment by MufriA** [comment]
https://logos.authenticatorplus.com/Uplay.png
