### ISSUE TITLE
Snapchat logo

### ISSUE THREAD

**Issue by ragnars-stuff** [authenticatorplus/logos#57]
Please provide below info, all are mandatory

1. https://www.snapchat.com/
2. Snapchat
3. ![snapchat-90px](https://user-images.githubusercontent.com/195335/29719280-5ec73480-89ad-11e7-9d6f-285e6eacc3a1.png)

**Comment by Ragnar79** [comment]
Duplicate

**Comment by ragnars-stuff** [comment]
Snapchat logo is not showing up for me.

Did a fresh install of oAndroind and app on Monday

**Comment by MufriA** [comment]
It should show, still not showing?
