### ISSUE TITLE
UnoEuro Logo

### ISSUE THREAD

**Issue by ragnars-stuff** [authenticatorplus/logos#58]
Please provide below info, all are mandatory

1. https://www.unoeuro.com/
2. UnoEuro
3. ![unoeuro-90px](https://user-images.githubusercontent.com/195335/29719399-c5f19cb8-89ad-11e7-8162-7109f62cfbcb.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
