### ISSUE TITLE
Backblaze

### ISSUE THREAD

**Issue by tseven** [authenticatorplus/logos#59]
Please provide below info, all are mandatory

1. https://www.backblaze.com
2. Backblaze
3. Upload the logo in 90x90, logo should be square
![5bnx_lvf_400x400](https://user-images.githubusercontent.com/311287/29730659-eb9f8d70-8995-11e7-8d6a-175a0c369cba.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
