### ISSUE TITLE
Gatehub

### ISSUE THREAD

**Issue by mach3taz0** [authenticatorplus/logos#61]
Please provide below info, all are mandatory

1. Gatehub.net
2. Gatehub
3. Upload the logo in 90x90, logo should be square

**Comment by mach3taz0** [comment]
![gatehub logo](https://user-images.githubusercontent.com/31739777/30174231-a85fe4aa-93fa-11e7-85db-7eb88338c179.jpg)

**Comment by mach3taz0** [comment]
thanks!!!

**Comment by mach3taz0** [comment]
anybody knows why it disappeared from app please?

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by Caligatio** [comment]
Did this disappear? I can't find it in the services list.
