### ISSUE TITLE
Need new logo for brittrex genesis hashflare

### ISSUE THREAD

**Issue by kteanboon** [authenticatorplus/logos#62]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
2. **Exact Service Name** displayed in the app
3. Upload the logo in 90x90, logo should be square

**Comment by joshgentry** [comment]
Looks like my issues #66 and #65 duplicate 2/3rds of this, but provide the necessary details for those two services

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
