### ISSUE TITLE
bitFlyer

### ISSUE THREAD

**Issue by joshgentry** [authenticatorplus/logos#64]
1. Website URL of server, even twitter page of the service too is fine
**https://bitflyer.jp/en/**

2. **Exact Service Name** displayed in the app
**bitFlyer**

3. Upload the logo in 90x90, logo should be square
![bitflyer-logo-scaled](https://user-images.githubusercontent.com/5125430/30632111-e9cafb2e-9e21-11e7-8f62-6026f9836c74.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
