### ISSUE TITLE
BITTREX

### ISSUE THREAD

**Issue by joshgentry** [authenticatorplus/logos#65]
1. Website URL of server, even twitter page of the service too is fine
**https://bittrex.com/**

2. **Exact Service Name** displayed in the app
**BITTREX**

3. Upload the logo in 90x90, logo should be square
![bittrex-logo-scaled](https://user-images.githubusercontent.com/5125430/30632127-fa84ba5e-9e21-11e7-9592-aa8f5d2f0fa3.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
