### ISSUE TITLE
Genesis Mining

### ISSUE THREAD

**Issue by joshgentry** [authenticatorplus/logos#66]
1. Website URL of server, even twitter page of the service too is fine
**https://www.genesis-mining.com/**

2. **Exact Service Name** displayed in the app
**Genesis Mining**

3. Upload the logo in 90x90, logo should be square
![genesis-mining-scaled](https://user-images.githubusercontent.com/5125430/30632345-b131344e-9e22-11e7-952d-edf551b1ff69.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by joshgentry** [comment]
@MufriA I don't see this (or the other requested logos) on the iOS app, is there a ceiling that prevents them from being listed, or some other issue?

Also, it appears the app hasn't been updated for 1+ years, is it abandoned?

**Comment by MufriA** [comment]
let me check why its not showing, its not abandoned, no much changes in app so no updates.

**Comment by joshgentry** [comment]
@MufriA have you had any time to look into this?
