### ISSUE TITLE
Sort services by alphabetical order

### ISSUE THREAD

**Issue by joshgentry** [authenticatorplus/logos#67]
Currently, and as the list grows, it can be difficult to find logos for services without scanning all logos in detail.

Sorting these logos by their service name alphabetically seems like it would be a good idea.

**Comment by MufriA** [comment]
You can try search for quick find, since we have customised order I suppose we can create a in-built category which sort A-Z.

**Comment by joshgentry** [comment]
@MufriA is search supported on iOS?

**Comment by MufriA** [comment]
No, its available only in android.
