### ISSUE TITLE
Trello logo request

### ISSUE THREAD

**Issue by jbondpdx** [authenticatorplus/logos#68]
Please provide below info, all are mandatory

1. trello.com
2. Trello

**Comment by jbondpdx** [comment]
![trello-mark-blue-small](https://user-images.githubusercontent.com/7927296/30660837-05cc9ce0-9df7-11e7-9ec7-ba2203791353.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
