### ISSUE TITLE
Fastmail Logo Request

### ISSUE THREAD

**Issue by Parev99** [authenticatorplus/logos#69]
Please provide below info, all are mandatory

1. Website URL of server: www.fastmail.com
2. **Exact Service Name** displayed in the app: Fastmail
![fastmail icon](https://user-images.githubusercontent.com/32204440/30757013-e336c200-9f81-11e7-8710-1872f7247a9e.png)

3. Upload the logo in 90x90, logo should be square  logo attached in 90x90

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
