### ISSUE TITLE
Discogs

### ISSUE THREAD

**Issue by CacheMinimal** [authenticatorplus/logos#7]
Please could you add an icon for the service "Discogs Login"?  The URL of their server is https://www.discogs.com/ and I attach a 90x90 PNG of their logo below:

![discogs](https://cloud.githubusercontent.com/assets/27230720/24875203/395062f2-1e1f-11e7-94c0-e4d87fad6da2.png)

Thanks in advance,

Ian.

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
