### ISSUE TITLE
Real-Debrid

### ISSUE THREAD

**Issue by dansleboby** [authenticatorplus/logos#71]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://real-debrid.com
2. **Exact Service Name** displayed in the app
Real-Debrid
3. Upload the logo in 90x90, logo should be square
![real-debrid](https://user-images.githubusercontent.com/4716382/30817511-01a1eb7c-a1e7-11e7-999f-caa0555be4cb.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
