### ISSUE TITLE
YoBit

### ISSUE THREAD

**Issue by dansleboby** [authenticatorplus/logos#72]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://yobit.net/en/
2. **Exact Service Name** displayed in the app
yobit.net
3. Upload the logo in 90x90, logo should be square
![yobit](https://user-images.githubusercontent.com/4716382/30817683-7dec14a0-a1e7-11e7-988f-5b6a1e008649.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
