### ISSUE TITLE
uPlay

### ISSUE THREAD

**Issue by dansleboby** [authenticatorplus/logos#73]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://uplay.ubi.com/
2. **Exact Service Name** displayed in the app
uplay
3. Upload the logo in 90x90, logo should be square
![uplay_filled1600](https://user-images.githubusercontent.com/4716382/30817817-eafad716-a1e7-11e7-8974-4148e25447f3.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
