### ISSUE TITLE
Android Wear - Pin display format

### ISSUE THREAD

**Issue by dansleboby** [authenticatorplus/logos#74]
Use same display format on Android Wear

![image](https://user-images.githubusercontent.com/4716382/30818107-a6cc5b2c-a1e8-11e7-8004-f61b588c938e.png)
![image](https://user-images.githubusercontent.com/4716382/30818118-ab183642-a1e8-11e7-8ea8-0e51a4371368.png)

**Comment by MufriA** [comment]
Good idea, will check it.
