### ISSUE TITLE
Moneybird (Dutch accounting software)

### ISSUE THREAD

**Issue by arikb** [authenticatorplus/logos#75]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine

https://moneybird.com
https://moneybird.nl

2. **Exact Service Name** displayed in the app

Moneybird

3. Upload the logo in 90x90, logo should be square

![moneybird logo](https://user-images.githubusercontent.com/1229613/30908934-9a1b8b26-a37f-11e7-9147-1fe55654670a.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
