### ISSUE TITLE
Porkbun logo

### ISSUE THREAD

**Issue by BitPopCoin** [authenticatorplus/logos#79]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
Porkbun.com
2. **Exact Service Name** displayed in the app
Porkbun
3. Upload the logo in 90x90, logo should be square
https://porkbun.com/images/porkbun_logo.svg

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
