### ISSUE TITLE
Seafile

### ISSUE THREAD

**Issue by Schnuecks** [authenticatorplus/logos#8]
Please provide below info, all are mandatory

1. seafile.com
2. Seafile
3. Logo taken from play store its transparent http://bit.ly/2opbuR8

![seafile](https://cloud.githubusercontent.com/assets/27301329/24924325/b29b2658-1ef4-11e7-8787-7f8c3908408e.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
