### ISSUE TITLE
Bittrex logo

### ISSUE THREAD

**Issue by BitPopCoin** [authenticatorplus/logos#80]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
Bittrex.com
2. **Exact Service Name** displayed in the app
Bittrex
3. Upload the logo in 90x90, logo should be square
https://bittrex.com/Content/img/logos/bittrex-logo-transparent.png

**Comment by MufriA** [comment]
Already part of repo.
