### ISSUE TITLE
reddit logo

### ISSUE THREAD

**Issue by Taubin** [authenticatorplus/logos#81]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine:
https://www.reddit.com/

2. **Exact Service Name** displayed in the app:
reddit

3. Upload the logo in 90x90, logo should be square:
![icon](https://user-images.githubusercontent.com/8891792/31153166-0d3a9134-a8fc-11e7-8565-91d99ab91945.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.

**Comment by Caligatio** [comment]
Is this logo live? It's not showing up in the Android app.
