### ISSUE TITLE
Auth0 Logo

### ISSUE THREAD

**Issue by lundsec** [authenticatorplus/logos#82]
1. Website URL of server, even twitter page of the service too is fine:
https://auth0.com

2. Exact Service Name displayed in the app:
Auth0

3. Upload the logo in 90x90, logo should be square:
![auth0 badge](https://user-images.githubusercontent.com/817235/31176660-eb89a166-a913-11e7-84ce-a655c9c1db7a.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
