### ISSUE TITLE
LDSAccess

### ISSUE THREAD

**Issue by psg190** [authenticatorplus/logos#83]
Please provide below info, all are mandatory

1. https://ident.lds.org/sso/UI/Login?service=credentials&goto=https%3a%2f%2fwww.lds.org%2fsigninout%2f%3flang%3deng
2. LDSAccess
3. Upload the logo in 90x90, logo should be square
![unnamed-90x90](https://user-images.githubusercontent.com/4184204/31597687-9e8ce8f2-b1fe-11e7-8d2e-2d0008fee2d5.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
