### ISSUE TITLE
GoToMyAccounts Logo

### ISSUE THREAD

**Issue by gtmadev** [authenticatorplus/logos#84]
Please provide below info, all are mandatory

1. https://www.gotomyaccounts.com
2. GoToMyAccounts
3. Upload the logo in 90x90, logo should be square
![gtma_logo_90](https://user-images.githubusercontent.com/30833539/31650015-146eeea4-b348-11e7-9964-5596860f3bb1.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
