### ISSUE TITLE
Ubiquiti Networks Logo

### ISSUE THREAD

**Issue by lars-1** [authenticatorplus/logos#85]
1. https://ubnt.com
2. Ubiquiti Networks - username
3.  
![ubiquiti_logo](https://user-images.githubusercontent.com/25988431/31838395-e901db54-b5dc-11e7-9ad8-dbf6cec63a38.png)

**Comment by MufriA** [comment]
I have included the requested icon, long press your account row, click logo button from toolbar and wait for icons to load till spinner goes off, select your service from the list.
