### ISSUE TITLE
Poloniex

### ISSUE THREAD

**Issue by EDIflyer** [authenticatorplus/logos#86]
1. https://www.poloniex.com/
2. [email]@poloniex.com
3. 
![8eqc8jrp_400x400](https://user-images.githubusercontent.com/13610277/31864162-ca3351ec-b750-11e7-93b6-d8bfc16cc1df.jpg)

**Comment by MufriA** [comment]
Added logo, you have to manually pick it, long press account and pick image icon from toolbar

**Comment by EDIflyer** [comment]
Not showing up in manual pick list

**Comment by MufriA** [comment]
Can you try now

**Comment by EDIflyer** [comment]
Poloniex.com shows up now, but no icon. Looks like WiFi signal with
exclamation mark (can't screenshot it due to app restrictions). Other site
logos all seem to load fine.

**Comment by MufriA** [comment]
Can you try now.

**Comment by EDIflyer** [comment]
Tried and still not showing up?

**Comment by MufriA** [comment]
Long press the account, pick image logo in toolbar and pick poloniex

**Comment by EDIflyer** [comment]
> Long press the account, pick image logo in toolbar and pick poloniex

Yes, as per your previous instructions that's what I did.  I can get a list of services up fine but Poloniex isn't showing (assuming they're alphabetically listed, they appear to be).  I'd send a screenshot but that's blocked from within the app.

**Comment by EDIflyer** [comment]
Not sure why closed, still not fixed? Just checked again and still not showing in list of custom icons...

**Comment by MufriA** [comment]
it will take sometime before its visible to everyone, just give some time and try again maybe now you can try.

**Comment by EDIflyer** [comment]
Lol it's actually showing twice now, as Poloniex and poloniex.com! Feel free to remove one of them.
