### ISSUE TITLE
HMRC Online

### ISSUE THREAD

**Issue by EDIflyer** [authenticatorplus/logos#87]
1. https://www.gov.uk/send-vat-return
2. HMRC - HMRC Online
3. 
![xxgpd77p_400x400](https://user-images.githubusercontent.com/13610277/31864167-d2594e44-b750-11e7-965e-2b5fa6da8d8d.png)

**Comment by MufriA** [comment]
Already part of repo

**Comment by EDIflyer** [comment]
Not showing up and can't find it in manual pick list either

**Comment by MufriA** [comment]
Is the service name correct, i mean exactly including spaces and cases?

**Comment by EDIflyer** [comment]
Is listed as "HMRC - HMRC Online" within the Authenticator Plus app.

**Comment by EDIflyer** [comment]
OK have just realised that the HMRC Online bit is editable within the AuthenticatorPlus app, so the core non-editable bit is just 'HMRC - '.  Not sure if that helps?

**Comment by MufriA** [comment]
Added it as custom logo, you can long press the logo and pick HMRC

**Comment by EDIflyer** [comment]
Yep, working now - in fact didn't even need to long-press and pick it, showed up automatically when I went in to the app?! 👍
