### ISSUE TITLE
Neostrada logo

### ISSUE THREAD

**Issue by D-on-GitHub** [authenticatorplus/logos#88]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine

https://www.neostrada.nl/
https://www.neostrada.com/

2. **Exact Service Name** displayed in the app

Account | NEOSTRADA

3. Upload the logo in 90x90, logo should be square

![40b3f8af9f03c9c3e7efdae79eaf9c99_400x400](https://user-images.githubusercontent.com/23340866/32170261-358248e4-bd74-11e7-80a7-b98548b86bd2.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
