### ISSUE TITLE
Sticky Password LOGO

### ISSUE THREAD

**Issue by laichihwei** [authenticatorplus/logos#90]
Please provide below info, all are mandatory

1. https://www.stickypassword.com/

2. Sticky Password

3. 
![sticky](https://user-images.githubusercontent.com/16130269/32262009-21e4fc56-bf0d-11e7-8dbc-5fe43a813fd0.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
