### ISSUE TITLE
Gitea Logo

### ISSUE THREAD

**Issue by kreativmonkey** [authenticatorplus/logos#93]
Can you pleas add the Gitea logo? Its a selfhosted service like github ore gitlab.

[Gitea Projekt](https://github.com/go-gitea/gitea)

**Comment by MufriA** [comment]
What's the service name displayed in app?

**Comment by kreativmonkey** [comment]
Sorry, i don't see that you have answered. The service name is "Gitea".

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
