### ISSUE TITLE
ConnectWise Logo

### ISSUE THREAD

**Issue by lukeskid** [authenticatorplus/logos#95]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
www.connectwise.com or https://na.myconnectwise.net/support/index.htm?Company=stateserorg
2. **Exact Service Name** displayed in the app
ConnectWise
3. Upload the logo in 90x90, logo should be square
![connectwise](https://user-images.githubusercontent.com/33637392/32745965-48fa0920-c882-11e7-812c-c04c2ea9c141.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
