### ISSUE TITLE
Solarwinds Logo

### ISSUE THREAD

**Issue by lukeskid** [authenticatorplus/logos#96]
Please provide below info, all are mandatory

1. Website URL of server, even twitter page of the service too is fine
https://www.solarwinds.com/
2. **Exact Service Name** displayed in the app
Solarwinds
3. Upload the logo in 90x90, logo should be square
![solarwinds](https://user-images.githubusercontent.com/33637392/32746119-af7c1792-c882-11e7-905e-2a71765653db.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
