### ISSUE TITLE
Team Password Manager Logo

### ISSUE THREAD

**Issue by IanCaunce** [authenticatorplus/logos#97]
Please provide below info, all are mandatory

1. http://teampasswordmanager.com/ (This is the product site. The tool itself is self hosted.)
2. TPM
3. 
![tpm](https://user-images.githubusercontent.com/10065879/32776850-df7312ee-c92b-11e7-8012-37137c52cbe5.png)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
