### ISSUE TITLE
Smartschool logo

### ISSUE THREAD

**Issue by maesben** [authenticatorplus/logos#98]
1. Website URL of server, even twitter page of the service too is fine
www.smartschool.be

2. **Exact Service Name** displayed in the app
Smartschool (I think, not sure where to find it. Smartschool has a seperate platform for each school).

3. Upload the logo in 90x90, logo should be square
![logo smartschool 90x90](https://user-images.githubusercontent.com/8598282/32945024-2749adfe-cb92-11e7-8e2b-c1fcebaade60.jpg)

**Comment by MufriA** [comment]
Merged to the logo repo, thanks for the contribution.
